In [1]:
import pandas as pd
people ={
    "first":["Corey","Jane","John"],
    "last":["Scheafer","Doe","Doe"],
    "email":["Corey@gmail.com","JaneDoe@gmail.com","JohnDoe@gmail.com"]
}
people_df = pd.DataFrame(people)

df = pd.read_csv("/home/luffy/Documents/Data_Science/Pandas/raw_data/stack_overflow_2024_data/survey_results_public.csv", index_col='ResponseId')
schema_df = pd.read_csv("/home/luffy/Documents/Data_Science/Pandas/raw_data/stack_overflow_2024_data/survey_results_schema.csv",index_col='qname')
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 500)

In [6]:
df['CompTotal'].median()

np.float64(110000.0)

In [8]:
df.median(numeric_only=True)

CompTotal              110000.0
WorkExp                     9.0
JobSatPoints_1             10.0
JobSatPoints_4              0.0
JobSatPoints_5              0.0
JobSatPoints_6             20.0
JobSatPoints_7             15.0
JobSatPoints_8             10.0
JobSatPoints_9              5.0
JobSatPoints_10             0.0
JobSatPoints_11             0.0
ConvertedCompYearly     65000.0
JobSat                      7.0
dtype: float64

In [9]:
df.describe()

           CompTotal       WorkExp  JobSatPoints_1  JobSatPoints_4  JobSatPoints_5  JobSatPoints_6  JobSatPoints_7  JobSatPoints_8  JobSatPoints_9  JobSatPoints_10  JobSatPoints_11  ConvertedCompYearly        JobSat
count   3.374000e+04  29658.000000    29324.000000    29393.000000    29411.000000    29450.000000     29448.00000    29456.000000    29456.000000     29450.000000     29445.000000         2.343500e+04  29126.000000
mean   2.963841e+145     11.466957       18.581094        7.522140       10.060857       24.343232        22.96522       20.278165       16.169432        10.955713         9.953948         8.615529e+04      6.935041
std    5.444117e+147      9.168709       25.966221       18.422661       21.833836       27.089360        27.01774       26.108110       24.845032        22.906263        21.775652         1.867570e+05      2.088259
min     0.000000e+00      0.000000        0.000000        0.000000        0.000000        0.000000         0.00000        0.000000        0.000000         0.000000         0.000000         1.000000e+00      0.000000
25%     6.000000e+04      4.000000        0.000000        0.000000        0.000000        0.000000         0.00000        0.000000        0.000000         0.000000         0.000000         3.271200e+04      6.000000
50%     1.100000e+05      9.000000       10.000000        0.000000        0.000000       20.000000        15.00000       10.000000        5.000000         0.000000         0.000000         6.500000e+04      7.000000
75%     2.500000e+05     16.000000       22.000000        5.000000       10.000000       30.000000        30.00000       25.000000       20.000000        10.000000        10.000000         1.079715e+05      8.000000
max    1.000000e+150     50.000000      100.000000      100.000000      100.000000      100.000000       100.00000      100.000000      100.000000       100.000000       100.000000         1.625660e+07     10.000000

In [23]:
df['SOAccount'].value_counts()

SOAccount
Yes                        45453
No                          9628
Not sure/can't remember     4479
Name: count, dtype: int64

In [24]:
df['SOAccount'].value_counts(normalize=True)

SOAccount
Yes                        0.763146
No                         0.161652
Not sure/can't remember    0.075201
Name: proportion, dtype: float64

In [25]:
df['Country'].value_counts()

Country
United States of America                                11095
Germany                                                  4947
India                                                    4231
United Kingdom of Great Britain and Northern Ireland     3224
Ukraine                                                  2672
France                                                   2110
Canada                                                   2104
Poland                                                   1534
Netherlands                                              1449
Brazil                                                   1375
Italy                                                    1341
Australia                                                1260
Spain                                                    1123
Sweden                                                   1016
Russian Federation                                        925
Switzerland                                               876
Austria                                                   791
Czech Republic                                            714
Israel                                                    604
Turkey                                                    546
Belgium                                                   526
Denmark                                                   504
Portugal                                                  470
Norway                                                    450
Romania                                                   439
Pakistan                                                  415
Iran, Islamic Republic of...                              411
China                                                     406
Mexico                                                    402
New Zealand                                               396
Hungary                                                   396
Greece                                                    389
Finland                                                   386
South Africa                                              358
Indonesia                                                 354
Argentina                                                 345
Bangladesh                                                327
Bulgaria                                                  319
Nigeria                                                   305
Viet Nam                                                  296
Japan                                                     288
Ireland                                                   270
Taiwan                                                    268
Egypt                                                     262
Slovakia                                                  248
Serbia                                                    245
Colombia                                                  217
Philippines                                               196
Croatia                                                   187
Lithuania                                                 183
Kenya                                                     180
Singapore                                                 177
Sri Lanka                                                 163
Malaysia                                                  161
Thailand                                                  147
South Korea                                               146
Hong Kong (S.A.R.)                                        146
Slovenia                                                  142
Nepal                                                     139
Chile                                                     133
United Arab Emirates                                      130
Latvia                                                    128
Estonia                                                   110
Morocco                                                    98
Belarus                                                    97
Georgia                                                    94
Uruguay                                                    94
Kazakhstan                                                 81
Algeria                                                    77
Peru                                                       75
Tunisia                                                    71
Ghana                                                      70
Venezuela, Bolivarian Republic of...                       69
Cyprus                                                     63
Bosnia and Herzegovina                                     62
Uzbekistan                                                 62
Ethiopia                                                   60
Armenia                                                    58
Republic of Korea                                          57
Afghanistan                                                56
Saudi Arabia                                               56
Costa Rica                                                 54
Ecuador                                                    54
Albania                                                    49
Dominican Republic                                         47
Lebanon                                                    46
Kyrgyzstan                                                 44
Iraq                                                       44
Nomadic                                                    43
Guatemala                                                  41
Luxembourg                                                 40
Jordan                                                     40
Uganda                                                     39
Paraguay                                                   39
Republic of Moldova                                        38
Republic of North Macedonia                                36
Bolivia                                                    32
Iceland                                                    31
Cameroon                                                   31
Syrian Arab Republic                                       30
Malta                                                      29
United Republic of Tanzania                                28
Montenegro                                                 27
Azerbaijan                                                 27
Zimbabwe                                                   26
Cuba                                                       23
Rwanda                                                     22
Cambodia                                                   22
Myanmar                                                    21
Nicaragua                                                  21
Angola                                                     20
El Salvador                                                19
Kosovo                                                     18
Yemen                                                      18
Panama                                                     18
Maldives                                                   16
Honduras                                                   16
Mauritius                                                  15
Palestine                                                  15
Andorra                                                    15
Qatar                                                      15
Zambia                                                     15
Madagascar                                                 14
Côte d'Ivoire                                              14
Isle of Man                                                13
Malawi                                                     12
Jamaica                                                    11
Turkmenistan                                               11
Benin                                                      11
Bahrain                                                    11
Mongolia                                                   10
Somalia                                                     9
Senegal                                                     9
Togo                                                        9
Kuwait                                                      8
Congo, Republic of the...                                   8
Trinidad and Tobago                                         8
Oman                                                        8
Mozambique                                                  7
Tajikistan                                                  7
Sudan                                                       7
Barbados                                                    6
Suriname                                                    5
Cape Verde                                                  5
Botswana                                                    5
Antigua and Barbuda                                         5
Namibia                                                     5
Mauritania                                                  5
Lao People's Democratic Republic                            4
Liechtenstein                                               4
Fiji                                                        4
Gabon                                                       4
Bahamas                                                     4
Swaziland                                                   4
Burkina Faso                                                4
Liberia                                                     4
Libyan Arab Jamahiriya                                      4
San Marino                                                  3
Sierra Leone                                                3
Democratic Republic of the Congo                            3
Burundi                                                     3
Bhutan                                                      3
Monaco                                                      3
Guyana                                                      3
North Korea                                                 3
Brunei Darussalam                                           3
Democratic People's Republic of Korea                       2
Mali                                                        2
Guinea-Bissau                                               2
Belize                                                      2
Dominica                                                    1
Papua New Guinea                                            1
Equatorial Guinea                                           1
Central African Republic                                    1
Samoa                                                       1
Niger                                                       1
Guinea                                                      1
Saint Kitts and Nevis                                       1
Lesotho                                                     1
Haiti                                                       1
Micronesia, Federated States of...                          1
Nauru                                                       1
Chad                                                        1
Djibouti                                                    1
Solomon Islands                                             1
Name: count, dtype: int64

In [27]:
country_grp = df.groupby(['Country'])

In [30]:
country_grp.get_group('India')

/tmp/ipykernel_10501/421256909.py:1: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  country_grp.get_group('India')

,MainBranch,Age,Employment,RemoteWork,Check,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,TechDoc,YearsCode,YearsCodePro,DevType,OrgSize,PurchaseInfluence,BuyNewTool,BuildvsBuy,TechEndorse,Country,Currency,CompTotal,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,EmbeddedHaveWorkedWith,EmbeddedWantToWorkWith,EmbeddedAdmired,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,MiscTechAdmired,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,ToolsTechAdmired,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,NEWCollabToolsAdmired,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackSyncHaveWorkedWith,OfficeStackSyncWantToWorkWith,OfficeStackSyncAdmired,AISearchDevHaveWorkedWith,AISearchDevWantToWorkWith,AISearchDevAdmired,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOHow,SOComm,AISelect,AISent,AIBen,AIAcc,AIComplex,AIToolCurrently Using,AIToolInterested in Using,AIToolNot interested in Using,AINextMuch more integrated,AINextNo change,AINextMore integrated,AINextLess integrated,AINextMuch less integrated,AIThreat,AIEthics,AIChallenges,TBranch,ICorPM,WorkExp,Knowledge_1,Knowledge_2,Knowledge_3,Knowledge_4,Knowledge_5,Knowledge_6,Knowledge_7,Knowledge_8,Knowledge_9,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,Frustration,ProfessionalTech,ProfessionalCloud,ProfessionalQuestion,Industry,JobSatPoints_1,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,SurveyLength,SurveyEase,ConvertedCompYearly,JobSat
ResponseId,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
18,I am a developer by profession,18-24 years old,"Independent contractor, freelancer, or self-em...",Remote,Apples,Hobby;Professional development or self-paced l...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Blogs;Coding sessions (live or recorded);How-t...,NaN,6,3,"Developer, front-end",NaN,NaN,NaN,NaN,NaN,India,NaN,NaN,HTML/CSS;JavaScript;TypeScript,HTML/CSS;JavaScript;TypeScript,HTML/CSS;JavaScript;TypeScript,NaN,NaN,NaN,Amazon Web Services (AWS);Digital Ocean;Fireba...,NaN,NaN,jQuery;Next.js;React,Next.js;React,Next.js;React,NaN,NaN,NaN,React Native,OpenGL;React Native,React Native,Docker;npm;Vite;Yarn,Docker;pnpm;Vite,Docker;Vite,VSCodium,VSCodium,VSCodium,Windows,Windows,Azure Devops,Azure Devops,Azure Devops,Google Meet;Microsoft Teams;Telegram;Whatsapp,Google Meet;Microsoft Teams,Google Meet;Microsoft Teams,ChatGPT,GitHub Copilot;Google Gemini,NaN,Stack Overflow;Stack Exchange,Less than once per month or monthly,Yes,Less than once per month or monthly,Quickly finding code solutions,Neutral,"No, but I plan to soon",Favorable,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I'm not sure,Replacing jobs without options for new employm...,Lack of executive buy-in,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
59,"I am not primarily a developer, but I write co...",18-24 years old,"Student, full-time",NaN,Apples,NaN,Some college/university study without earning ...,"Other online resources (e.g., videos, blogs, f...",Stack Overflow;Coding sessions (live or record...,NaN,4,NaN,Student,NaN,NaN,NaN,NaN,NaN,India,NaN,NaN,C;C++;HTML/CSS;JavaScript;Python;SQL,C++;HTML/CSS;Python,C++;HTML/CSS;Python,SQLite,NaN,NaN,NaN,NaN,NaN,Django;Node.js,Django,Django,Arduino,Arduino,Arduino,NaN,NaN,NaN,npm,NaN,NaN,Code::Blocks;PyCharm;Visual Studio Code,Code::Blocks;Visual Studio Code,Code::Blocks;Visual Studio Code,Android;Ubuntu;Windows,Windows,NaN,NaN,NaN,Discord;Telegram;Whatsapp,Whatsapp,Whatsapp,ChatGPT,GitHub Copilot;Google Gemini,NaN,Stack Overflow;Stack Exchange,A few times per week,Yes,Less than once per month or monthly,Quickly finding code solutions;Finding reliabl...,Neutral,Yes,Favorable,Increase productivity;Greater efficiency;Make ...,Somewhat trust,Neither good or bad at handling complex tasks,Debugging and getting help;Search for answers,NaN,NaN,NaN,Search for answers,Debugging and getting help,NaN,NaN,No,Circulating misinformation or disinformation;M...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
76,I am learning to code,25-34 years old,"Not employed, but looking for work",NaN,Apples,NaN,Some college/university study without earning ...,Online Courses or Certification;Coding Bootcamp,NaN,NaN,4,NaN,Designer,NaN,NaN,NaN,NaN,NaN,India,NaN,NaN,HTML/CSS;JavaScript,Dart;Kotlin;Swift,NaN,MongoDB,NaN,NaN,Firebase;Heroku;VMware,Digital Ocean,NaN,Node.js;React,NaN,NaN,NaN,NaN,NaN,Flutter;Ionic;React Native,NaN,NaN,npm,NaN,NaN,Android Studio;IntelliJ IDEA;Notepad++;Sublime...,NaN,NaN,Android;Ubuntu;Windows,NaN,Asana;Clickup;Miro;Monday.com,Notion;Stack Overflow for Teams,NaN,Skype;Slack;Whatsapp;Zoom,Discord;Google Chat,NaN,Google Gemini,NaN,NaN,Stack Overflow;Stack Exchange,Daily or almost daily,Yes,A few times per week,Quickly finding code solutions;Finding reliabl...,Neutral,"No, but I plan to soon",Favorable,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,Replacing jobs without options for new employm...,Don’t trust the output or answers;Not everyone...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
90,I am learning to code,25-34 years old,"Employed, full-time",In-person,Apples,Contribute to open-source projects,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","School (i.e., University, College, etc);Online...",NaN,NaN,2,NaN,Security professional,NaN,NaN,NaN,NaN,NaN,India,NaN,NaN,C;C++;HTML/CSS;Java;JavaScript;PHP;SQL;Visual ...,HTML/CSS;Java;JavaScript;PHP;SQL;Visual Basic ...,HTML/CSS;Java;JavaScript;PHP;SQL;Visual Basic ...,Elasticsearch;MySQL;Oracle,Elasticsearch;MySQL;Oracle,Elasticsearch;MySQL;Oracle,Managed Hosting;VMware,NaN,NaN,ASP.NET;CodeIgniter;Node.js;WordPress,CodeIgniter;Node.js,CodeIgniter;Node.js,Rasberry Pi,Rasberry Pi,Rasberry Pi,NumPy,NaN,NaN,npm,NaN,NaN,Nano;Netbeans;Notepad++;Sublime Text;Vim;Visua...,Nano;Notepad++;Visual Studio Code,Nano;Notepad++;Visual Studio Code,Debian;Ubuntu;Windows;Windows Subsystem for Li...,Debian;Ubuntu;Windows;Windows Subsystem for Li...,Stack Overflow for Teams,NaN,NaN,Cisco Webex Teams;Discord;Google Meet;Microsof...,Discord;Google Meet;Microsoft Teams;Telegram;W...,Discord;Google Meet;Microsoft Teams;Telegram;W...,ChatGPT;Snyk Code,ChatGPT;Snyk Code,ChatGPT;Snyk Code,Stack Exchange,A few times per month or weekly,Yes,Less than once per month or monthly,Finding reliable guidance from community-vette...,"Yes, definitely","No, but I plan to soon",Favorable,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,Circulating misinformation or disinformation;R...,Not everyone uses them,Yes,Individual contributor,3.0,Agree,Neither agree nor disagree,Agree,Agree,Agree,Agree,Neither agree nor disagree,Agree,Agree,Never,1-2 times a week,Never,60-120 minutes a day,Less than 15 minutes a day,None of these,Observability tools;Knowledge sharing community,Hybrid (on-prem and cloud),AI-powered search (free),Higher Education,80.0,90.0,90.0,50.0,70.0,50.0,50.0,50.0,80.0,Appropriate in length,Easy,NaN,8.0
97,I am a developer by profession,25-34 years old,"Employed, full-time",Remote,Apples,Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","School (i.e., University, College, etc)",NaN,NaN,11,7,"Developer, mobile",NaN,NaN,NaN,NaN,NaN,India,NaN,NaN,Bash/Shell (all shells);C#;JavaScript,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,.NET (5+) ;.NET MAUI,NaN,NaN,NuGet,NaN,NaN,Visual Studio;Visual Studio Code;Xcode,Rider,NaN,Android;Windows,Android;iOS;MacOS;Windows,Azure Devops,NaN,NaN,Microsoft Teams,NaN,NaN,ChatGPT;GitHub Copilot,ChatGPT;GitHub Copilot;Google Gemini;Meta AI,ChatGPT;GitHub Copilot,Stack Overflow,A few times per week,Yes,Less than once per month or monthly,Quickly finding code solutions;Finding reliabl...,"Yes, somewhat",Yes,Very favorable,Increase productivity;Greater efficiency;Impro...,Somewhat trust,"Good, but not great at handling complex tasks",Writing code;Documenting code;Search for answe...,Learning about a codebase;Project planning;Deb...,NaN,Generating content or synthetic data,NaN,Writing code;Documenting code;Search for answers,NaN,NaN,Yes,Biased results that do not represent diverse v...,"AI tools lack context of codebase, internal a...",Yes,Individual contributor,7.0,Agree,Neither agree nor disagree,Disagree,Agree,Neither agree nor disagree,Agree,Agree,Agree,Strongly disagree,1-2 times a week,1-2 times a week,1-2 times a week,30-60 minutes a day,30-60 minutes a day,Amount of technical debt;Tracking my work;Show...,DevOps function;Developer portal or other cent...,Cloud only (single or multi-cloud),A coworker,Software Development,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Too long,Easy,NaN,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65340,"I am not primarily a developer, but I write co...",18-24 years old,"Student, full-time",NaN,Apples,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Social Media;How-to vi...,API document(s) and/or SDK document(s),4,2,"Developer, mobile",NaN,NaN,NaN,NaN,NaN,India,NaN,NaN,C;C#;C++;Go;HTML/CSS;JavaScript;Objective-C;Py...,NaN,NaN,Cassandra;Firebase Realtime Database;MariaDB;M...,NaN,NaN,Amazon Web Services (AWS);Cloudflare;Firebase;...,NaN,NaN,Django;Flask;Next.js;Node.js;React,NaN,NaN,Arduino;Rasberry Pi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Stack Overflow;Stack Exchange,Daily or almost daily,No,NaN,Quickly finding code solutions;Finding reliabl...,Neutral,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65384,I am learning to code,18-24 years old,"Not employed, but looking for work",NaN,Apples,NaN,Some college/university study without earning ...,"School (i.e., University, College, etc)",NaN,NaN,9,NaN,Student,NaN,NaN,NaN,NaN,NaN,India,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Stack Exchange,Less than once per month or monthly,Yes,I have never participated in Q&A on Stack Over...,Quickly finding code solutions;Finding reliabl...,"Yes, definitely",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65414,I am learning to code,18-24 years old,"Student, full-time",NaN,Apples,NaN,"Secondary school (e.g. American high school, G...","Other online resources (e.g., videos, blogs, f...",Social Media;How-to videos;Video-based Online ...,NaN,3,NaN,Student,NaN,NaN,NaN,NaN,NaN,India,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Stack Overflow;Stack Exchange,A few times per month or weekly,No,NaN,Quickly finding code solutions,"No, not at all",Yes,Unsure,Increase productivity;Speed up learning;Make w...,Somewhat trust,Bad at handling complex tasks,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65416,I code primarily as a hobby,35-44 years old,I prefer not to say,NaN,Apples,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Blogs;Stack Overflow;Social Media;Video-based ...,NaN,4,NaN,System administrator,NaN,NaN,NaN,NaN,NaN,India,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Stack Overflow,A few times per week,Yes,Less than once per month or monthly,Quickly finding code solutions;Engage with com...,"Yes, somewhat",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65429,I am a developer by profession,25-34 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Profe...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;Other online ...,Technical documentation;Books;Interactive tuto...,API document(s) and/or SDK document(s);User gu...,4,7,"Developer, back-end","1,000 to 4,999 employees",I have some influence,Start a free trial;Ask developers I know/work ...,NaN,Integrated developer community;Frequent update...,India,INR\tIndian rupee,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Stack Overflow;Stack Exchange,A few times per month or weekly,No,NaN,Quickly finding code solutions;Finding reliabl...,Neutral,"No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [34]:
country_grp['OpSysPersonal use'].value_counts(normalize=True).loc['India']

OpSysPersonal use
Windows                                                    0.209848
MacOS                                                      0.069444
Android;Windows                                            0.065152
Ubuntu;Windows                                             0.060354
Ubuntu                                                     0.046970
                                                             ...
iOS;iPadOS;Ubuntu                                          0.000253
iOS;iPadOS;Ubuntu;Windows                                  0.000253
iPadOS;MacOS                                               0.000253
iPadOS;Ubuntu                                              0.000253
iPadOS;Ubuntu;Windows;Windows Subsystem for Linux (WSL)    0.000253
Name: proportion, Length: 506, dtype: float64

In [41]:
country_grp['ConvertedCompYearly'].median().loc['India']

np.float64(16749.0)

In [42]:
country_grp['ConvertedCompYearly'].agg(['median','mean'])

                                                       median          mean
Country
Afghanistan                                            3438.0  5.057250e+03
Albania                                               35341.0  3.920755e+04
Algeria                                                7120.0  9.183670e+04
Andorra                                              123517.0  1.235170e+05
Angola                                                 1754.0  1.366333e+03
Antigua and Barbuda                                  126120.0  1.261200e+05
Argentina                                             30000.0  4.365684e+04
Armenia                                               27865.0  3.937610e+04
Australia                                             95465.5  1.063751e+05
Austria                                               64551.5  7.386823e+04
Azerbaijan                                            23555.0  3.445400e+04
Bahamas                                                   NaN           NaN
Bahrain                                               37213.0  3.721300e+04
Bangladesh                                             6840.5  1.177631e+04
Barbados                                                  6.0  6.000000e+00
Belarus                                               21205.5  4.288521e+04
Belgium                                               64444.0  7.235561e+04
Belize                                                    NaN           NaN
Benin                                                  1499.5  1.499500e+03
Bhutan                                                 2751.0  2.751000e+03
Bolivia                                               12138.0  2.751058e+04
Bosnia and Herzegovina                                34548.0  3.765263e+04
Botswana                                              34004.5  3.400450e+04
Brazil                                                23945.0  5.121623e+04
Brunei Darussalam                                     31880.0  3.188000e+04
Bulgaria                                              46959.0  4.903479e+04
Burkina Faso                                           2181.5  2.181500e+03
Burundi                                                4170.0  4.170000e+03
Cambodia                                              22800.0  5.051467e+04
Cameroon                                               2869.0  4.851800e+03
Canada                                                87231.0  1.023487e+05
Cape Verde                                            17112.0  1.492333e+04
Central African Republic                                 44.0  4.400000e+01
Chad                                                      NaN           NaN
Chile                                                 32765.5  3.418508e+04
China                                                 41392.0  5.021530e+04
Colombia                                              18672.5  3.572940e+04
Congo, Republic of the...                             15750.0  1.575000e+04
Costa Rica                                            56668.5  7.248988e+04
Croatia                                               45111.0  5.684207e+04
Cuba                                                  11700.0  1.946030e+04
Cyprus                                                75184.0  1.155929e+05
Czech Republic                                        47865.0  5.433681e+04
Côte d'Ivoire                                          9160.0  1.873543e+04
Democratic People's Republic of Korea                 32640.0  3.264000e+04
Democratic Republic of the Congo                      12000.0  1.200000e+04
Denmark                                               89137.0  9.744101e+04
Djibouti                                                  NaN           NaN
Dominica                                                  NaN           NaN
Dominican Republic                                    14142.0  3.152674e+04
Ecuador                                               18000.0  2.833600e+04
Egypt                                                  9721.0  2.181621e+04
El Salvador                                           50400.0  4.908571e+04
Equatorial Guinea                                         NaN           NaN
Estonia                                               60555.5  6.234379e+04
Ethiopia                                               5572.0  9.345702e+05
Fiji                                                  22526.0  2.252600e+04
Finland                                               64444.0  7.189501e+04
France                                                53703.0  6.276120e+04
Gabon                                               2000000.0  2.000000e+06
Georgia                                               50170.0  5.326320e+04
Germany                                               73036.0  7.705455e+04
Ghana                                                  4800.0  1.091947e+04
Greece                                                37485.0  4.877690e+04
Guatemala                                             26993.0  3.800543e+04
Guinea                                                    NaN           NaN
Guinea-Bissau                                             NaN           NaN
Guyana                                                 6021.0  6.021000e+03
Haiti                                                 90000.0  9.000000e+04
Honduras                                              10646.0  1.797100e+04
Hong Kong (S.A.R.)                                    53437.0  7.430700e+04
Hungary                                               39404.0  4.870280e+04
Iceland                                               66537.0  7.145580e+04
India                                                 16749.0  3.051361e+04
Indonesia                                              7360.0  1.646742e+04
Iran, Islamic Republic of...                          20000.0  1.016500e+05
Iraq                                                  11450.0  2.143082e+04
Ireland                                               91295.0  9.682346e+04
Isle of Man                                           82802.0  9.004544e+04
Israel                                               113334.0  1.199820e+05
Italy                                                 41619.5  4.978024e+04
Jamaica                                               28910.5  2.733900e+04
Japan                                                 57598.0  6.913313e+04
Jordan                                                44441.0  4.988786e+04
Kazakhstan                                            36555.0  8.167110e+04
Kenya                                                 11163.0  6.275838e+04
Kosovo                                                10311.0  1.173400e+04
Kuwait                                                54617.0  5.461700e+04
Kyrgyzstan                                             3563.5  1.821412e+04
Lao People's Democratic Republic                       4080.0  4.080000e+03
Latvia                                                49407.0  5.313788e+04
Lebanon                                               20000.0  2.437538e+04
Lesotho                                               15600.0  1.560000e+04
Liberia                                                   NaN           NaN
Libyan Arab Jamahiriya                                 9897.0  9.897000e+03
Liechtenstein                                         59498.0  5.949800e+04
Lithuania                                             63584.5  6.945952e+04
Luxembourg                                            96288.0  1.004711e+05
Madagascar                                             6264.0  7.400600e+03
Malawi                                                 7176.0  7.176000e+03
Malaysia                                              18116.0  2.441330e+04
Maldives                                              18700.0  1.711800e+04
Mali                                                  43620.0  4.362000e+04
Malta                                                 56388.0  6.125510e+04
Mauritania                                            12061.5  1.206150e+04
Mauritius                                             12081.0  2.598562e+04
Mexico                                                30860.0  3.854050e+04
Micronesia, Federated States of...                        NaN           NaN
Monaco                                                    NaN           NaN
Mongolia                                              19936.5  1.993650e+04
Montenegro                                            38666.0  5.680809e+04
Morocco                                               10251.0  1.262785e+04
Mozambique                                            36612.0  2.865967e+04
Myanmar                                                2716.0  2.691167e+03
Namibia                                               36953.5  3.695350e+04
Nauru                                                     NaN           NaN
Nepal                                                  7470.0  9.886914e+03
Netherlands                                           69814.0  8.231797e+04
New Zealand                                           74362.0  8.205424e+04
Nicaragua                                             28000.0  5.096575e+04
Niger                                                     NaN           NaN
Nigeria                                                2857.0  1.041561e+04
Nomadic                                               75184.5  8.323975e+04
North Korea                                               NaN           NaN
Norway                                                79552.0  8.350338e+04
Oman                                                  12989.0  1.298900e+04
Pakistan                                               8614.0  6.938141e+04
Palestine                                             30000.0  4.929400e+04
Panama                                                45000.0  4.640000e+04
Papua New Guinea                                          NaN           NaN
Paraguay                                              24149.0  4.466573e+04
Peru                                                  26406.0  4.275041e+04
Philippines                                           20000.5  3.106542e+04
Poland                                                55535.5  6.190153e+04
Portugal                                              49944.0  6.062775e+04
Qatar                                                 68658.0  6.997600e+04
Republic of Korea                                     43519.5  4.110617e+04
Republic of Moldova                                   44991.0  5.050955e+04
Republic of North Macedonia                           27043.0  3.518673e+04
Romania                                               49304.0  5.563699e+04
Russian Federation                                    26891.0  3.604486e+04
Rwanda                                                20802.0  2.215462e+04
Saint Kitts and Nevis                                     NaN           NaN
Samoa                                                 85620.0  8.562000e+04
San Marino                                                NaN           NaN
Saudi Arabia                                          67193.0  7.452781e+04
Senegal                                               22015.5  2.201550e+04
Serbia                                                37984.5  4.615000e+04
Sierra Leone                                              1.0  1.000000e+00
Singapore                                            103482.0  1.361505e+05
Slovakia                                              42962.0  4.804748e+04
Slovenia                                              53703.0  5.168625e+04
Solomon Islands                                           NaN           NaN
Somalia                                               12500.0  1.250000e+04
South Africa                                          44769.0  1.323939e+05
South Korea                                           38804.5  5.014732e+04
Spain                                                 51555.0  5.817174e+04
Sri Lanka                                             10031.0  1.571864e+04
Sudan                                                 18665.0  1.866500e+04
Suriname                                              16000.0  1.600000e+04
Swaziland                                                 NaN           NaN
Sweden                                                57230.0  6.483214e+04
Switzerland                                          111417.0  1.185547e+05
Syrian Arab Republic                                   5254.0  1.630556e+04
Taiwan                                                30884.0  1.273200e+05
Tajikistan                                             7086.0  7.086000e+03
Thailand                                              34712.5  4.185818e+04
Togo                                                     14.0  1.400000e+01
Trinidad and Tobago                                   37403.0  3.740300e+04
Tunisia                                                6874.5  1.101905e+04
Turkey                                                24755.5  3.577860e+04
Turkmenistan                                           8547.0  2.312186e+04
Uganda                                                 9019.0  2.641880e+04
Ukraine                                               26903.5  3.945577e+04
United Arab Emirates                                  60715.0  6.837733e+04
United Kingdom of Great Britain and Northern Ir...    84076.0  1.026033e+05
United Republic of Tanzania                           11472.0  1.895629e+04
United States of America                             143000.0  1.610723e+05
Uruguay                                               75994.0  7.994314e+04
Uzbekistan                                            10000.0  2.835711e+04
Venezuela, Bolivarian Republic of...                  10800.0  2.013737e+04
Viet Nam                                              12288.5  1.880328e+04
Yemen                                                  5333.0  1.649840e+04
Zambia                                                 2280.0  1.705440e+04
Zimbabwe                                              18000.0  2.968182e+04

In [49]:
df['LanguageHaveWorkedWith'].str.contains('Python').sum()

30795

In [50]:
country_grp['LanguageHaveWorkedWith'].str.contains('Python').sum()

AttributeError: 'SeriesGroupBy' object has no attribute 'str'

In [55]:
country_grp['LanguageHaveWorkedWith'].apply(lambda x: x.str.contains('Python').sum())

Country
Afghanistan                                               26
Albania                                                   10
Algeria                                                   37
Andorra                                                    8
Angola                                                     9
Antigua and Barbuda                                        0
Argentina                                                163
Armenia                                                   23
Australia                                                658
Austria                                                  410
Azerbaijan                                                14
Bahamas                                                    2
Bahrain                                                    4
Bangladesh                                               144
Barbados                                                   1
Belarus                                                   36
Belgium                                                  279
Belize                                                     2
Benin                                                      2
Bhutan                                                     2
Bolivia                                                   11
Bosnia and Herzegovina                                    22
Botswana                                                   1
Brazil                                                   643
Brunei Darussalam                                          3
Bulgaria                                                 112
Burkina Faso                                               0
Burundi                                                    1
Cambodia                                                   9
Cameroon                                                  14
Canada                                                  1120
Cape Verde                                                 1
Central African Republic                                   1
Chad                                                       1
Chile                                                     77
China                                                    233
Colombia                                                 103
Congo, Republic of the...                                  6
Costa Rica                                                23
Croatia                                                   86
Cuba                                                       9
Cyprus                                                    33
Czech Republic                                           333
Côte d'Ivoire                                              4
Democratic People's Republic of Korea                      1
Democratic Republic of the Congo                           2
Denmark                                                  241
Djibouti                                                   0
Dominica                                                   1
Dominican Republic                                        18
Ecuador                                                   28
Egypt                                                    139
El Salvador                                               12
Equatorial Guinea                                          0
Estonia                                                   55
Ethiopia                                                  26
Fiji                                                       2
Finland                                                  207
France                                                  1187
Gabon                                                      2
Georgia                                                   44
Germany                                                 2647
Ghana                                                     34
Greece                                                   180
Guatemala                                                 22
Guinea                                                     0
Guinea-Bissau                                              0
Guyana                                                     2
Haiti                                                      0
Honduras                                                   6
Hong Kong (S.A.R.)                                        77
Hungary                                                  193
Iceland                                                   18
India                                                   2128
Indonesia                                                174
Iran, Islamic Republic of...                             182
Iraq                                                      17
Ireland                                                  147
Isle of Man                                                6
Israel                                                   360
Italy                                                    699
Jamaica                                                    5
Japan                                                    167
Jordan                                                    16
Kazakhstan                                                30
Kenya                                                    106
Kosovo                                                     8
Kuwait                                                     5
Kyrgyzstan                                                22
Lao People's Democratic Republic                           0
Latvia                                                    60
Lebanon                                                   22
Lesotho                                                    1
Liberia                                                    3
Libyan Arab Jamahiriya                                     3
Liechtenstein                                              1
Lithuania                                                 59
Luxembourg                                                22
Madagascar                                                 5
Malawi                                                     4
Malaysia                                                  77
Maldives                                                   9
Mali                                                       1
Malta                                                      7
Mauritania                                                 4
Mauritius                                                  6
Mexico                                                   195
Micronesia, Federated States of...                         0
Monaco                                                     2
Mongolia                                                   5
Montenegro                                                10
Morocco                                                   57
Mozambique                                                 4
Myanmar                                                    4
Namibia                                                    2
Nauru                                                      0
Nepal                                                     53
Netherlands                                              700
New Zealand                                              197
Nicaragua                                                  8
Niger                                                      1
Nigeria                                                  132
Nomadic                                                   21
North Korea                                                2
Norway                                                   211
Oman                                                       3
Pakistan                                                 173
Palestine                                                  4
Panama                                                     5
Papua New Guinea                                           0
Paraguay                                                  18
Peru                                                      33
Philippines                                               83
Poland                                                   783
Portugal                                                 204
Qatar                                                      5
Republic of Korea                                         29
Republic of Moldova                                       12
Republic of North Macedonia                               13
Romania                                                  185
Russian Federation                                       485
Rwanda                                                    13
Saint Kitts and Nevis                                      1
Samoa                                                      1
San Marino                                                 1
Saudi Arabia                                              19
Senegal                                                    3
Serbia                                                   101
Sierra Leone                                               2
Singapore                                                110
Slovakia                                                 107
Slovenia                                                  67
Solomon Islands                                            0
Somalia                                                    3
South Africa                                             162
South Korea                                               87
Spain                                                    554
Sri Lanka                                                 87
Sudan                                                      4
Suriname                                                   1
Swaziland                                                  2
Sweden                                                   459
Switzerland                                              466
Syrian Arab Republic                                      12
Taiwan                                                   137
Tajikistan                                                 4
Thailand                                                  74
Togo                                                       3
Trinidad and Tobago                                        4
Tunisia                                                   31
Turkey                                                   248
Turkmenistan                                               6
Uganda                                                    23
Ukraine                                                  963
United Arab Emirates                                      64
United Kingdom of Great Britain and Northern Ireland    1638
United Republic of Tanzania                               12
United States of America                                6251
Uruguay                                                   43
Uzbekistan                                                21
Venezuela, Bolivarian Republic of...                      25
Viet Nam                                                 138
Yemen                                                     10
Zambia                                                     8
Zimbabwe                                                  17
Name: LanguageHaveWorkedWith, dtype: int64

In [56]:
country_respondents = df['Country'].value_counts()

In [58]:
country_uses_python = country_grp['LanguageHaveWorkedWith'].apply(lambda x: x.str.contains('Python').sum())

In [59]:
python_df = pd.concat([country_respondents, country_uses_python], axis='columns')

In [60]:
python_df

                                                    count  LanguageHaveWorkedWith
Country
United States of America                            11095                    6251
Germany                                              4947                    2647
India                                                4231                    2128
United Kingdom of Great Britain and Northern Ir...   3224                    1638
Ukraine                                              2672                     963
France                                               2110                    1187
Canada                                               2104                    1120
Poland                                               1534                     783
Netherlands                                          1449                     700
Brazil                                               1375                     643
Italy                                                1341                     699
Australia                                            1260                     658
Spain                                                1123                     554
Sweden                                               1016                     459
Russian Federation                                    925                     485
Switzerland                                           876                     466
Austria                                               791                     410
Czech Republic                                        714                     333
Israel                                                604                     360
Turkey                                                546                     248
Belgium                                               526                     279
Denmark                                               504                     241
Portugal                                              470                     204
Norway                                                450                     211
Romania                                               439                     185
Pakistan                                              415                     173
Iran, Islamic Republic of...                          411                     182
China                                                 406                     233
Mexico                                                402                     195
New Zealand                                           396                     197
Hungary                                               396                     193
Greece                                                389                     180
Finland                                               386                     207
South Africa                                          358                     162
Indonesia                                             354                     174
Argentina                                             345                     163
Bangladesh                                            327                     144
Bulgaria                                              319                     112
Nigeria                                               305                     132
Viet Nam                                              296                     138
Japan                                                 288                     167
Ireland                                               270                     147
Taiwan                                                268                     137
Egypt                                                 262                     139
Slovakia                                              248                     107
Serbia                                                245                     101
Colombia                                              217                     103
Philippines                                           196                      83
Croatia                                               187                      86
Lithuania                                             183                      59
Kenya                                                 180                     106
Singapore                                             177                     110
Sri Lanka                                             163                      87
Malaysia                                              161                      77
Thailand                                              147                      74
South Korea                                           146                      87
Hong Kong (S.A.R.)                                    146                      77
Slovenia                                              142                      67
Nepal                                                 139                      53
Chile                                                 133                      77
United Arab Emirates                                  130                      64
Latvia                                                128                      60
Estonia                                               110                      55
Morocco                                                98                      57
Belarus                                                97                      36
Georgia                                                94                      44
Uruguay                                                94                      43
Kazakhstan                                             81                      30
Algeria                                                77                      37
Peru                                                   75                      33
Tunisia                                                71                      31
Ghana                                                  70                      34
Venezuela, Bolivarian Republic of...                   69                      25
Cyprus                                                 63                      33
Bosnia and Herzegovina                                 62                      22
Uzbekistan                                             62                      21
Ethiopia                                               60                      26
Armenia                                                58                      23
Republic of Korea                                      57                      29
Afghanistan                                            56                      26
Saudi Arabia                                           56                      19
Costa Rica                                             54                      23
Ecuador                                                54                      28
Albania                                                49                      10
Dominican Republic                                     47                      18
Lebanon                                                46                      22
Kyrgyzstan                                             44                      22
Iraq                                                   44                      17
Nomadic                                                43                      21
Guatemala                                              41                      22
Luxembourg                                             40                      22
Jordan                                                 40                      16
Uganda                                                 39                      23
Paraguay                                               39                      18
Republic of Moldova                                    38                      12
Republic of North Macedonia                            36                      13
Bolivia                                                32                      11
Iceland                                                31                      18
Cameroon                                               31                      14
Syrian Arab Republic                                   30                      12
Malta                                                  29                       7
United Republic of Tanzania                            28                      12
Montenegro                                             27                      10
Azerbaijan                                             27                      14
Zimbabwe                                               26                      17
Cuba                                                   23                       9
Rwanda                                                 22                      13
Cambodia                                               22                       9
Myanmar                                                21                       4
Nicaragua                                              21                       8
Angola                                                 20                       9
El Salvador                                            19                      12
Kosovo                                                 18                       8
Yemen                                                  18                      10
Panama                                                 18                       5
Maldives                                               16                       9
Honduras                                               16                       6
Mauritius                                              15                       6
Palestine                                              15                       4
Andorra                                                15                       8
Qatar                                                  15                       5
Zambia                                                 15                       8
Madagascar                                             14                       5
Côte d'Ivoire                                          14                       4
Isle of Man                                            13                       6
Malawi                                                 12                       4
Jamaica                                                11                       5
Turkmenistan                                           11                       6
Benin                                                  11                       2
Bahrain                                                11                       4
Mongolia                                               10                       5
Somalia                                                 9                       3
Senegal                                                 9                       3
Togo                                                    9                       3
Kuwait                                                  8                       5
Congo, Republic of the...                               8                       6
Trinidad and Tobago                                     8                       4
Oman                                                    8                       3
Mozambique                                              7                       4
Tajikistan                                              7                       4
Sudan                                                   7                       4
Barbados                                                6                       1
Suriname                                                5                       1
Cape Verde                                              5                       1
Botswana                                                5                       1
Antigua and Barbuda                                     5                       0
Namibia                                                 5                       2
Mauritania                                              5                       4
Lao People's Democratic Republic                        4                       0
Liechtenstein                                           4                       1
Fiji                                                    4                       2
Gabon                                                   4                       2
Bahamas                                                 4                       2
Swaziland                                               4                       2
Burkina Faso                                            4                       0
Liberia                                                 4                       3
Libyan Arab Jamahiriya                                  4                       3
San Marino                                              3                       1
Sierra Leone                                            3                       2
Democratic Republic of the Congo                        3                       2
Burundi                                                 3                       1
Bhutan                                                  3                       2
Monaco                                                  3                       2
Guyana                                                  3                       2
North Korea                                             3                       2
Brunei Darussalam                                       3                       3
Democratic People's Republic of Korea                   2                       1
Mali                                                    2                       1
Guinea-Bissau                                           2                       0
Belize                                                  2                       2
Dominica                                                1                       1
Papua New Guinea                                        1                       0
Equatorial Guinea                                       1                       0
Central African Republic                                1                       1
Samoa                                                   1                       1
Niger                                                   1                       1
Guinea                                                  1                       0
Saint Kitts and Nevis                                   1                       1
Lesotho                                                 1                       1
Haiti                                                   1                       0
Micronesia, Federated States of...                      1                       0
Nauru                                                   1                       0
Chad                                                    1                       1
Djibouti                                                1                       0
Solomon Islands                                         1                       0

In [63]:
python_df.rename(columns={'count':'NumRespondents', 'LanguageHaveWorkedWith':'NumKnowsPython'}, inplace=True)

In [64]:
python_df

                                                    NumRespondents  NumKnowsPython
Country
United States of America                                     11095            6251
Germany                                                       4947            2647
India                                                         4231            2128
United Kingdom of Great Britain and Northern Ir...            3224            1638
Ukraine                                                       2672             963
France                                                        2110            1187
Canada                                                        2104            1120
Poland                                                        1534             783
Netherlands                                                   1449             700
Brazil                                                        1375             643
Italy                                                         1341             699
Australia                                                     1260             658
Spain                                                         1123             554
Sweden                                                        1016             459
Russian Federation                                             925             485
Switzerland                                                    876             466
Austria                                                        791             410
Czech Republic                                                 714             333
Israel                                                         604             360
Turkey                                                         546             248
Belgium                                                        526             279
Denmark                                                        504             241
Portugal                                                       470             204
Norway                                                         450             211
Romania                                                        439             185
Pakistan                                                       415             173
Iran, Islamic Republic of...                                   411             182
China                                                          406             233
Mexico                                                         402             195
New Zealand                                                    396             197
Hungary                                                        396             193
Greece                                                         389             180
Finland                                                        386             207
South Africa                                                   358             162
Indonesia                                                      354             174
Argentina                                                      345             163
Bangladesh                                                     327             144
Bulgaria                                                       319             112
Nigeria                                                        305             132
Viet Nam                                                       296             138
Japan                                                          288             167
Ireland                                                        270             147
Taiwan                                                         268             137
Egypt                                                          262             139
Slovakia                                                       248             107
Serbia                                                         245             101
Colombia                                                       217             103
Philippines                                                    196              83
Croatia                                                        187              86
Lithuania                                                      183              59
Kenya                                                          180             106
Singapore                                                      177             110
Sri Lanka                                                      163              87
Malaysia                                                       161              77
Thailand                                                       147              74
South Korea                                                    146              87
Hong Kong (S.A.R.)                                             146              77
Slovenia                                                       142              67
Nepal                                                          139              53
Chile                                                          133              77
United Arab Emirates                                           130              64
Latvia                                                         128              60
Estonia                                                        110              55
Morocco                                                         98              57
Belarus                                                         97              36
Georgia                                                         94              44
Uruguay                                                         94              43
Kazakhstan                                                      81              30
Algeria                                                         77              37
Peru                                                            75              33
Tunisia                                                         71              31
Ghana                                                           70              34
Venezuela, Bolivarian Republic of...                            69              25
Cyprus                                                          63              33
Bosnia and Herzegovina                                          62              22
Uzbekistan                                                      62              21
Ethiopia                                                        60              26
Armenia                                                         58              23
Republic of Korea                                               57              29
Afghanistan                                                     56              26
Saudi Arabia                                                    56              19
Costa Rica                                                      54              23
Ecuador                                                         54              28
Albania                                                         49              10
Dominican Republic                                              47              18
Lebanon                                                         46              22
Kyrgyzstan                                                      44              22
Iraq                                                            44              17
Nomadic                                                         43              21
Guatemala                                                       41              22
Luxembourg                                                      40              22
Jordan                                                          40              16
Uganda                                                          39              23
Paraguay                                                        39              18
Republic of Moldova                                             38              12
Republic of North Macedonia                                     36              13
Bolivia                                                         32              11
Iceland                                                         31              18
Cameroon                                                        31              14
Syrian Arab Republic                                            30              12
Malta                                                           29               7
United Republic of Tanzania                                     28              12
Montenegro                                                      27              10
Azerbaijan                                                      27              14
Zimbabwe                                                        26              17
Cuba                                                            23               9
Rwanda                                                          22              13
Cambodia                                                        22               9
Myanmar                                                         21               4
Nicaragua                                                       21               8
Angola                                                          20               9
El Salvador                                                     19              12
Kosovo                                                          18               8
Yemen                                                           18              10
Panama                                                          18               5
Maldives                                                        16               9
Honduras                                                        16               6
Mauritius                                                       15               6
Palestine                                                       15               4
Andorra                                                         15               8
Qatar                                                           15               5
Zambia                                                          15               8
Madagascar                                                      14               5
Côte d'Ivoire                                                   14               4
Isle of Man                                                     13               6
Malawi                                                          12               4
Jamaica                                                         11               5
Turkmenistan                                                    11               6
Benin                                                           11               2
Bahrain                                                         11               4
Mongolia                                                        10               5
Somalia                                                          9               3
Senegal                                                          9               3
Togo                                                             9               3
Kuwait                                                           8               5
Congo, Republic of the...                                        8               6
Trinidad and Tobago                                              8               4
Oman                                                             8               3
Mozambique                                                       7               4
Tajikistan                                                       7               4
Sudan                                                            7               4
Barbados                                                         6               1
Suriname                                                         5               1
Cape Verde                                                       5               1
Botswana                                                         5               1
Antigua and Barbuda                                              5               0
Namibia                                                          5               2
Mauritania                                                       5               4
Lao People's Democratic Republic                                 4               0
Liechtenstein                                                    4               1
Fiji                                                             4               2
Gabon                                                            4               2
Bahamas                                                          4               2
Swaziland                                                        4               2
Burkina Faso                                                     4               0
Liberia                                                          4               3
Libyan Arab Jamahiriya                                           4               3
San Marino                                                       3               1
Sierra Leone                                                     3               2
Democratic Republic of the Congo                                 3               2
Burundi                                                          3               1
Bhutan                                                           3               2
Monaco                                                           3               2
Guyana                                                           3               2
North Korea                                                      3               2
Brunei Darussalam                                                3               3
Democratic People's Republic of Korea                            2               1
Mali                                                             2               1
Guinea-Bissau                                                    2               0
Belize                                                           2               2
Dominica                                                         1               1
Papua New Guinea                                                 1               0
Equatorial Guinea                                                1               0
Central African Republic                                         1               1
Samoa                                                            1               1
Niger                                                            1               1
Guinea                                                           1               0
Saint Kitts and Nevis                                            1               1
Lesotho                                                          1               1
Haiti                                                            1               0
Micronesia, Federated States of...                               1               0
Nauru                                                            1               0
Chad                                                             1               1
Djibouti                                                         1               0
Solomon Islands                                                  1               0

In [65]:
python_df['percentageknowspython'] = (python_df['NumKnowsPython'] / python_df['NumRespondents']) * 100

In [66]:
python_df

                                                    NumRespondents  NumKnowsPython  percentageknowspython
Country
United States of America                                     11095            6251              56.340694
Germany                                                       4947            2647              53.507176
India                                                         4231            2128              50.295438
United Kingdom of Great Britain and Northern Ir...            3224            1638              50.806452
Ukraine                                                       2672             963              36.040419
France                                                        2110            1187              56.255924
Canada                                                        2104            1120              53.231939
Poland                                                        1534             783              51.043025
Netherlands                                                   1449             700              48.309179
Brazil                                                        1375             643              46.763636
Italy                                                         1341             699              52.125280
Australia                                                     1260             658              52.222222
Spain                                                         1123             554              49.332146
Sweden                                                        1016             459              45.177165
Russian Federation                                             925             485              52.432432
Switzerland                                                    876             466              53.196347
Austria                                                        791             410              51.833123
Czech Republic                                                 714             333              46.638655
Israel                                                         604             360              59.602649
Turkey                                                         546             248              45.421245
Belgium                                                        526             279              53.041825
Denmark                                                        504             241              47.817460
Portugal                                                       470             204              43.404255
Norway                                                         450             211              46.888889
Romania                                                        439             185              42.141230
Pakistan                                                       415             173              41.686747
Iran, Islamic Republic of...                                   411             182              44.282238
China                                                          406             233              57.389163
Mexico                                                         402             195              48.507463
New Zealand                                                    396             197              49.747475
Hungary                                                        396             193              48.737374
Greece                                                         389             180              46.272494
Finland                                                        386             207              53.626943
South Africa                                                   358             162              45.251397
Indonesia                                                      354             174              49.152542
Argentina                                                      345             163              47.246377
Bangladesh                                                     327             144              44.036697
Bulgaria                                                       319             112              35.109718
Nigeria                                                        305             132              43.278689
Viet Nam                                                       296             138              46.621622
Japan                                                          288             167              57.986111
Ireland                                                        270             147              54.444444
Taiwan                                                         268             137              51.119403
Egypt                                                          262             139              53.053435
Slovakia                                                       248             107              43.145161
Serbia                                                         245             101              41.224490
Colombia                                                       217             103              47.465438
Philippines                                                    196              83              42.346939
Croatia                                                        187              86              45.989305
Lithuania                                                      183              59              32.240437
Kenya                                                          180             106              58.888889
Singapore                                                      177             110              62.146893
Sri Lanka                                                      163              87              53.374233
Malaysia                                                       161              77              47.826087
Thailand                                                       147              74              50.340136
South Korea                                                    146              87              59.589041
Hong Kong (S.A.R.)                                             146              77              52.739726
Slovenia                                                       142              67              47.183099
Nepal                                                          139              53              38.129496
Chile                                                          133              77              57.894737
United Arab Emirates                                           130              64              49.230769
Latvia                                                         128              60              46.875000
Estonia                                                        110              55              50.000000
Morocco                                                         98              57              58.163265
Belarus                                                         97              36              37.113402
Georgia                                                         94              44              46.808511
Uruguay                                                         94              43              45.744681
Kazakhstan                                                      81              30              37.037037
Algeria                                                         77              37              48.051948
Peru                                                            75              33              44.000000
Tunisia                                                         71              31              43.661972
Ghana                                                           70              34              48.571429
Venezuela, Bolivarian Republic of...                            69              25              36.231884
Cyprus                                                          63              33              52.380952
Bosnia and Herzegovina                                          62              22              35.483871
Uzbekistan                                                      62              21              33.870968
Ethiopia                                                        60              26              43.333333
Armenia                                                         58              23              39.655172
Republic of Korea                                               57              29              50.877193
Afghanistan                                                     56              26              46.428571
Saudi Arabia                                                    56              19              33.928571
Costa Rica                                                      54              23              42.592593
Ecuador                                                         54              28              51.851852
Albania                                                         49              10              20.408163
Dominican Republic                                              47              18              38.297872
Lebanon                                                         46              22              47.826087
Kyrgyzstan                                                      44              22              50.000000
Iraq                                                            44              17              38.636364
Nomadic                                                         43              21              48.837209
Guatemala                                                       41              22              53.658537
Luxembourg                                                      40              22              55.000000
Jordan                                                          40              16              40.000000
Uganda                                                          39              23              58.974359
Paraguay                                                        39              18              46.153846
Republic of Moldova                                             38              12              31.578947
Republic of North Macedonia                                     36              13              36.111111
Bolivia                                                         32              11              34.375000
Iceland                                                         31              18              58.064516
Cameroon                                                        31              14              45.161290
Syrian Arab Republic                                            30              12              40.000000
Malta                                                           29               7              24.137931
United Republic of Tanzania                                     28              12              42.857143
Montenegro                                                      27              10              37.037037
Azerbaijan                                                      27              14              51.851852
Zimbabwe                                                        26              17              65.384615
Cuba                                                            23               9              39.130435
Rwanda                                                          22              13              59.090909
Cambodia                                                        22               9              40.909091
Myanmar                                                         21               4              19.047619
Nicaragua                                                       21               8              38.095238
Angola                                                          20               9              45.000000
El Salvador                                                     19              12              63.157895
Kosovo                                                          18               8              44.444444
Yemen                                                           18              10              55.555556
Panama                                                          18               5              27.777778
Maldives                                                        16               9              56.250000
Honduras                                                        16               6              37.500000
Mauritius                                                       15               6              40.000000
Palestine                                                       15               4              26.666667
Andorra                                                         15               8              53.333333
Qatar                                                           15               5              33.333333
Zambia                                                          15               8              53.333333
Madagascar                                                      14               5              35.714286
Côte d'Ivoire                                                   14               4              28.571429
Isle of Man                                                     13               6              46.153846
Malawi                                                          12               4              33.333333
Jamaica                                                         11               5              45.454545
Turkmenistan                                                    11               6              54.545455
Benin                                                           11               2              18.181818
Bahrain                                                         11               4              36.363636
Mongolia                                                        10               5              50.000000
Somalia                                                          9               3              33.333333
Senegal                                                          9               3              33.333333
Togo                                                             9               3              33.333333
Kuwait                                                           8               5              62.500000
Congo, Republic of the...                                        8               6              75.000000
Trinidad and Tobago                                              8               4              50.000000
Oman                                                             8               3              37.500000
Mozambique                                                       7               4              57.142857
Tajikistan                                                       7               4              57.142857
Sudan                                                            7               4              57.142857
Barbados                                                         6               1              16.666667
Suriname                                                         5               1              20.000000
Cape Verde                                                       5               1              20.000000
Botswana                                                         5               1              20.000000
Antigua and Barbuda                                              5               0               0.000000
Namibia                                                          5               2              40.000000
Mauritania                                                       5               4              80.000000
Lao People's Democratic Republic                                 4               0               0.000000
Liechtenstein                                                    4               1              25.000000
Fiji                                                             4               2              50.000000
Gabon                                                            4               2              50.000000
Bahamas                                                          4               2              50.000000
Swaziland                                                        4               2              50.000000
Burkina Faso                                                     4               0               0.000000
Liberia                                                          4               3              75.000000
Libyan Arab Jamahiriya                                           4               3              75.000000
San Marino                                                       3               1              33.333333
Sierra Leone                                                     3               2              66.666667
Democratic Republic of the Congo                                 3               2              66.666667
Burundi                                                          3               1              33.333333
Bhutan                                                           3               2              66.666667
Monaco                                                           3               2              66.666667
Guyana                                                           3               2              66.666667
North Korea                                                      3               2              66.666667
Brunei Darussalam                                                3               3             100.000000
Democratic People's Republic of Korea                            2               1              50.000000
Mali                                                             2               1              50.000000
Guinea-Bissau                                                    2               0               0.000000
Belize                                                           2               2             100.000000
Dominica                                                         1               1             100.000000
Papua New Guinea                                                 1               0               0.000000
Equatorial Guinea                                                1               0               0.000000
Central African Republic                                         1               1             100.000000
Samoa                                                            1               1             100.000000
Niger                                                            1               1             100.000000
Guinea                                                           1               0               0.000000
Saint Kitts and Nevis                                            1               1             100.000000
Lesotho                                                          1               1             100.000000
Haiti                                                            1               0               0.000000
Micronesia, Federated States of...                               1               0               0.000000
Nauru                                                            1               0               0.000000
Chad                                                             1               1             100.000000
Djibouti                                                         1               0               0.000000
Solomon Islands                                                  1               0               0.000000